import { sql } from "drizzle-orm";
import {
  bigint,
  boolean,
  check,
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  primaryKey,
  real,
  smallint,
  text,
  timestamp,
  uniqueIndex,
  varchar,
  vector,
} from "drizzle-orm/pg-core";

// The single source of truth for data shapes (docs/01-architecture.md#data-model).
// Types are derived from here — never defined in parallel.
//
// Conventions (docs/07-conventions.md#time-and-ids):
// - primary keys are bigint identity columns, generated by the database
// - timestamps are timestamptz, stored in UTC
//
// Indexes are plain ascending b-trees; Postgres scans them backwards for
// `ORDER BY … DESC`. Avoid `.desc()` here: it yields DESC NULLS LAST, which a
// plain `ORDER BY … DESC` (NULLS FIRST) cannot use.
//
// Migrations are additive once deployed: add columns, never rename or drop in
// the same step.

const id = () => bigint("id", { mode: "number" }).primaryKey().generatedAlwaysAsIdentity();
const foreignId = (name: string) => bigint(name, { mode: "number" });
const timestamptz = (name: string) => timestamp(name, { withTimezone: true });
const createdAt = () => timestamptz("created_at").notNull().defaultNow();

/** voyage-3.5-lite (ADR-009). Changing models means a full reindex. */
export const EMBEDDING_DIMENSIONS = 1024;

export const sourceHealth = pgEnum("source_health", ["unknown", "ok", "degraded", "failing"]);
export const matchMethod = pgEnum("match_method", ["seed", "url", "trigram", "embedding", "llm"]);
export const interactionKind = pgEnum("interaction_kind", [
  "impression",
  "open",
  "dwell",
  "save",
  "hide",
  "up",
  "down",
]);
export const notificationChannel = pgEnum("notification_channel", ["telegram"]);
export const jobStatus = pgEnum("job_status", ["running", "succeeded", "failed"]);

/** Everyone who may read Astra. One profile, a few readers (ADR-001). */
export const users = pgTable("users", {
  id: id(),
  name: text("name").notNull(),
  createdAt: createdAt(),
});

/** Registry of sources. Adding one means an adapter plus a row here. */
export const sources = pgTable("sources", {
  id: id(),
  /** Stable key, e.g. "hackernews". */
  slug: text("slug").notNull().unique(),
  /** Which Collector adapter serves this source. */
  collector: text("collector").notNull(),
  name: text("name").notNull(),
  /** Adapter-specific settings (feed URLs, queries, filters); the adapter parses it. */
  config: jsonb("config").$type<Record<string, unknown>>().notNull().default({}),
  enabled: boolean("enabled").notNull().default(true),
  health: sourceHealth("health").notNull().default("unknown"),
  lastRunAt: timestamptz("last_run_at"),
  createdAt: createdAt(),
});

/** Collected entries, one row per source per find. */
export const rawItems = pgTable(
  "raw_items",
  {
    id: id(),
    sourceId: foreignId("source_id")
      .notNull()
      .references(() => sources.id),
    externalId: text("external_id").notNull(),
    url: text("url").notNull(),
    /** Set by the normaliser; the key for stage-1 clustering. */
    canonicalUrl: text("canonical_url"),
    title: text("title").notNull(),
    /** Never the full text — at most 500 characters (docs/02-sources.md#legal). */
    bodySnippet: varchar("body_snippet", { length: 500 }),
    author: text("author"),
    publishedAt: timestamptz("published_at"),
    /** Source-specific counters, e.g. { points: 412, comments: 120 }. */
    engagement: jsonb("engagement").$type<Record<string, number>>().notNull().default({}),
    fetchedAt: timestamptz("fetched_at").notNull().defaultNow(),
    /** The source's original record, for reprocessing — minus any full article text. */
    raw: jsonb("raw").$type<unknown>().notNull(),
  },
  (t) => [
    uniqueIndex("raw_items_source_external_key").on(t.sourceId, t.externalId),
    index("raw_items_canonical_url_idx").on(t.canonicalUrl),
    index("raw_items_fetched_at_idx").on(t.fetchedAt),
  ],
);

export interface StoryEntities {
  orgs: string[];
  people: string[];
  tech: string[];
}

/** Where a story happens — the data behind the globe markers (ADR-012). */
export interface StoryGeo {
  place: string;
  lat: number;
  lon: number;
}

/** The condensed event — the unit a human actually sees. */
export const stories = pgTable(
  "stories",
  {
    id: id(),
    clusterKey: text("cluster_key"),
    title: text("title").notNull(),
    summaryShort: text("summary_short"),
    summaryDeep: text("summary_deep"),
    explainer: text("explainer"),
    topics: text("topics").array().notNull().default([]),
    entities: jsonb("entities").$type<StoryEntities>(),
    geo: jsonb("geo").$type<StoryGeo>(),
    /** 0–100, set by triage. */
    importance: smallint("importance"),
    embedding: vector("embedding", { dimensions: EMBEDDING_DIMENSIONS }),
    /** Which model produced `embedding` (ADR-009). */
    embeddingModel: text("embedding_model"),
    lang: text("lang"),
    firstSeenAt: timestamptz("first_seen_at").notNull().defaultNow(),
    lastActivityAt: timestamptz("last_activity_at").notNull().defaultNow(),
    /** Denormalised count of story_items — the ranking needs it on every query. */
    sourceCount: smallint("source_count").notNull().default(1),
    enrichedAt: timestamptz("enriched_at"),
  },
  (t) => [
    // The HNSW index on `embedding` and the trigram index on `title` arrive with
    // clustering in phase 2, where their parameters get measured.
    index("stories_last_activity_at_idx").on(t.lastActivityAt),
    index("stories_importance_idx").on(t.importance),
    check("stories_importance_range", sql`${t.importance} between 0 and 100`),
  ],
);

/** Which raw items make up a story, and how each was matched. */
export const storyItems = pgTable(
  "story_items",
  {
    storyId: foreignId("story_id")
      .notNull()
      .references(() => stories.id, { onDelete: "cascade" }),
    rawItemId: foreignId("raw_item_id")
      .notNull()
      .references(() => rawItems.id, { onDelete: "cascade" }),
    /** "seed" for the item that founded the story. */
    matchMethod: matchMethod("match_method").notNull(),
    confidence: real("confidence"),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.storyId, t.rawItemId] }),
    index("story_items_raw_item_idx").on(t.rawItemId),
    check("story_items_confidence_range", sql`${t.confidence} between 0 and 1`),
  ],
);

/** Behavioural signals for personalisation. */
export const interactions = pgTable(
  "interactions",
  {
    id: id(),
    userId: foreignId("user_id")
      .notNull()
      .references(() => users.id),
    storyId: foreignId("story_id")
      .notNull()
      .references(() => stories.id, { onDelete: "cascade" }),
    kind: interactionKind("kind").notNull(),
    /** Seconds for `dwell`; unused by the other kinds. */
    value: real("value"),
    createdAt: createdAt(),
  },
  (t) => [
    index("interactions_user_created_at_idx").on(t.userId, t.createdAt),
    index("interactions_story_idx").on(t.storyId),
  ],
);

/** The personalisation profile — one row per user, in practice one (ADR-001). */
export const profiles = pgTable("profiles", {
  userId: foreignId("user_id")
    .primaryKey()
    .references(() => users.id),
  /** Set explicitly, e.g. { "ai-infra": 1, crypto: 0 }. */
  topicWeights: jsonb("topic_weights").$type<Record<string, number>>().notNull().default({}),
  /** Learned implicitly from interactions. */
  embedding: vector("embedding", { dimensions: EMBEDDING_DIMENSIONS }),
  updatedAt: timestamptz("updated_at")
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

/** Every push that went out, and why. */
export const notifications = pgTable(
  "notifications",
  {
    id: id(),
    userId: foreignId("user_id")
      .notNull()
      .references(() => users.id),
    storyId: foreignId("story_id")
      .notNull()
      .references(() => stories.id, { onDelete: "cascade" }),
    channel: notificationChannel("channel").notNull(),
    sentAt: timestamptz("sent_at").notNull().defaultNow(),
    /** Without this, the rules engine is undebuggable. */
    reason: text("reason").notNull(),
    feedback: text("feedback"),
  },
  (t) => [index("notifications_story_idx").on(t.storyId)],
);

/** Telemetry for every job run — the basis for cost tracking and alerting. */
export const jobRuns = pgTable(
  "job_runs",
  {
    id: id(),
    jobName: text("job_name").notNull(),
    /** BullMQ's job ID and attempt number, to correlate with the logs. */
    jobId: text("job_id"),
    attempt: smallint("attempt").notNull().default(1),
    status: jobStatus("status").notNull().default("running"),
    startedAt: timestamptz("started_at").notNull().defaultNow(),
    finishedAt: timestamptz("finished_at"),
    itemsIn: integer("items_in").notNull().default(0),
    itemsOut: integer("items_out").notNull().default(0),
    costUsd: numeric("cost_usd", { precision: 12, scale: 6, mode: "number" }).notNull().default(0),
    error: text("error"),
  },
  (t) => [index("job_runs_job_name_started_at_idx").on(t.jobName, t.startedAt)],
);

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type Source = typeof sources.$inferSelect;
export type NewSource = typeof sources.$inferInsert;
export type RawItem = typeof rawItems.$inferSelect;
export type NewRawItem = typeof rawItems.$inferInsert;
export type Story = typeof stories.$inferSelect;
export type NewStory = typeof stories.$inferInsert;
export type StoryItem = typeof storyItems.$inferSelect;
export type NewStoryItem = typeof storyItems.$inferInsert;
export type Interaction = typeof interactions.$inferSelect;
export type NewInteraction = typeof interactions.$inferInsert;
export type Profile = typeof profiles.$inferSelect;
export type NewProfile = typeof profiles.$inferInsert;
export type Notification = typeof notifications.$inferSelect;
export type NewNotification = typeof notifications.$inferInsert;
export type JobRun = typeof jobRuns.$inferSelect;
export type NewJobRun = typeof jobRuns.$inferInsert;
